// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCY39x013tBXMJ1LAsGWUgm8EaZEdqgXdA',
    appId: '1:769667920629:web:57398fa983be3c53514bbc',
    messagingSenderId: '769667920629',
    projectId: 'stride-app-b7d10',
    authDomain: 'stride-app-b7d10.firebaseapp.com',
    storageBucket: 'stride-app-b7d10.firebasestorage.app',
    measurementId: 'G-33XP7QC5X0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfruITdnoMbp4eqBoyVXiIz4irUdV7VHo',
    appId: '1:769667920629:android:a8bcd0140c67af99514bbc',
    messagingSenderId: '769667920629',
    projectId: 'stride-app-b7d10',
    storageBucket: 'stride-app-b7d10.firebasestorage.app',
  );
}
